export const POPULATE_RECIPE_RESULTS = "POPULATE_RECIPE_RESULTS";

export const ADD_RECIPE_RESULT = "ADD_RECIPE_RESULT";

export const CLEAR_RECIPE_RESULTS = "CLEAR_RECIPE_RESULTS";

export const SET_SEARCH = "SET_SEARCH";

export const SET_ACTIVE_RECIPE = "SET_ACTIVE_RECIPE";
